### ISSUE TITLE
Getting System.ArgumentOutOfRangeException when creating reader with large stream 

### ISSUE THREAD

**Issue by BenyErnest** [nietras/Sep#24]
Hi,
I'm getting:
 

> System.ArgumentOutOfRangeException: minimumLength ('-688018613') must be a non-negative value. (Parameter 'minimumLength')
      Actual value was -688018613.
         at System.ArgumentOutOfRangeException.ThrowNegative[T](T value, String paramName)
         at System.ArgumentOutOfRangeException.ThrowIfNegative[T](T value, String paramName)
         at System.Buffers.SharedArrayPool`1.Rent(Int32 minimumLength)
         at nietras.SeparatedValues.SepReader..ctor(SepReaderOptions options, TextReader reader)
         at nietras.SeparatedValues.SepReaderExtensions.From(SepReaderOptions options, TextReader reader)
         at nietras.SeparatedValues.SepReaderExtensions.From(SepReaderOptions options, Stream stream)

 when creating a Sep Reader with a very large Stream object:

```
using var reader = Sep.Reader().From(stream);
```

Is there a limit to how big it should be?

**Comment by nietras** [comment]
@BenyErnest thanks for reporting this, no there should be no limit on stream length, this is probably a bug in an internal buffer length calculation. Will take a look.
